export interface User {
  id?: number;              // optional, generated by backend
  username: string;
  email: string;
  password?: string;         // for signup/login only, not stored
  role: 'student' | 'admin';
}

export interface AuthResponse {
  token: string;
  user: User;
}
